import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {Sidebar} from "../../components/Sidebar"

import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Dashboard",
  description: "Generated by ME",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <div className="flex flex-row bg-slate-100">
          <Sidebar/>
        
        <div className=" flex h-screen"></div>
          {children}
        </div>
          
        </body>
    </html>
  );
}

